apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shrek
  name: shrek
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-volume
      mountPath: /shrek
    resources:
      limits:
        cpu: "1.0"
        memory: "256Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"
  - image: alpine
    name: alpine
    volumeMounts:
    - name: alpine-volume
      mountPath: /fiona
    resources:
      limits:
        cpu: "1.0"
        memory: "256Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"
    command: ["sleep", "3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: nginx-volume
    emptyDir:
      sizeLimit: 500Mi
  - name: alpine-volume
    emptyDir:
      sizeLimit: 500Mi

